# Code Audit System Configuration

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434"
  models:
    coder: "deepseek-coder:6.7b"
    reasoner: "deepseek-r1:1.5b"
    scaler: "deepscaler"
  timeout: 60
  max_retries: 3

# Scanning Configuration
scanning:
  max_file_size: 2000  # characters
  supported_extensions:
    - .py
    - .js
    - .jsx
    - .ts
    - .tsx
    - .java
    - .cpp
    - .c
    - .php
    - .rb
    - .go
    - .rs
    - .cs
    - .swift
  
  exclude_patterns:
    - "*/node_modules/*"
    - "*/venv/*"
    - "*/env/*"
    - "*/.git/*"
    - "*/build/*"
    - "*/dist/*"
    - "*/__pycache__/*"
    - "*.min.js"
    - "*.min.css"

# Security Analysis
security:
  severity_weights:
    CRITICAL: 15
    HIGH: 10
    MEDIUM: 5
    LOW: 2
  
  pattern_confidence:
    SQL_INJECTION: 0.9
    XSS: 0.8
    HARDCODED_SECRETS: 0.95
    COMMAND_INJECTION: 0.9

# Quality Analysis
quality:
  thresholds:
    function_length: 50  # lines
    parameter_count: 5
    cyclomatic_complexity: 10
    nesting_depth: 4
  
  severity_weights:
    HIGH: 5
    MEDIUM: 3
    LOW: 1

# Reporting
reporting:
  database_path: "audit_results.db"
  export_formats:
    - json
    - csv
    - html
    - pdf
  
  compliance_standards:
    - PCI-DSS
    - SOX
    - GDPR
    - HIPAA
    - ISO-27001

# Dashboard
dashboard:
  port: 8501
  host: "0.0.0.0"
  theme: "light"
  auto_refresh: 30  # seconds

# Performance
performance:
  max_workers: 4
  chunk_size: 100
  cache_enabled: true
  cache_ttl: 3600  # seconds